version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rating-youtube-thumbnails
    ports:
      - '5432:5432'