spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/rating-youtube-thumbnails

jwt:
  secret: UKf5sq!#WaNX7Rfv$Y%&iO^IRf2INSR1

youtube-api:
  base-url: https://youtube.googleapis.com/youtube/v3
  key: AIzaSyBpWoXdFi_eprveOLLupKpGp5xEt8LNaTY