spring:
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/youtube-thumbnail-ranking
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    properties:
      auth: false
      mail:
        smtp:
          starttls:
            enable: false

    host: localhost
    port: 1025

email-sender:
  sender: no-reply@youtube-thumbnail-ranking.com

email-verification:
  expiration-hours: 24
  max-number-of-mails-per-hour: 5

jwt:
  issuer: youtube-thumbnail-ranking-test
  token-expiration-hours: 1
  key:
    public: classpath:certs/public.pem
    private: classpath:certs/private.pem

youtube-api:
  base-url: https://youtube.googleapis.com/youtube/v3
  key:

rating:
  base-points: 1400
  k-parameter: 32

game:
  duration: 15